# Generated by Django 6.0.5 on 2026-06-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='videos/raw/'),
        ),
    ]
