# Generated by Django 6.0.5 on 2026-06-14 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("video", "0002_video_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="video_url",
        ),
    ]
