# Generated by Django 6.0.5 on 2026-05-27 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
